stages:
  - build

build_linux:
    stage: build
    tags:
      - linux-all
    only:
      - tags
    script:
      - ./build-package ${CI_COMMIT_TAG}
    artifacts:
        name: "bashclub-zsync_${CI_COMMIT_TAG}_all.deb"
        paths:
          - "bashclub-zsync_${CI_COMMIT_TAG}_all.deb"
