#!/bin/bash
version=$1
package=bashclub-zsync

deb_package=${package}_${version}_all.deb

echo "$(date) creating DEBIBAN/control..."
cat << EOF > $package/DEBIAN/control
Package: $package
Version: $version
Architecture: all
Essential: no
Priority: optional
Depends: bashclub-checkzfs, openssh-server, zfs-auto-snapshot, zfsutils-linux
Maintainer: bashclub
Description: The deb package for $package $version maintained from bashclub.
EOF

echo "$(date) fixing acls"
chmod 755 $package/DEBIAN/p*

# remove bashclub-zsync-config from package
rm $package/usr/bin/bashclub-zsync-config
rm $package/usr/bin/bashclub-zsync.py

# add license and changelog
mkdir -p ./$package/usr/share/doc/$package/copyright
cp LICENSE ./$package/usr/share/doc/$package/copyright
cp CHANGELOG.md ./$package/usr/share/doc/$package/

dpkg-deb --build $package $deb_package
